/**
 * BibcodeQueryLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ReturnBibcode
 *
 * @constructor
 */
angular.module('BibcodeQueryLib')
    .factory('ReturnBibcode', ['BaseModel', ReturnBibcodeModel]);

    function ReturnBibcodeModel(BaseModel) {
        var ReturnBibcode = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.body = this.getValue(obj.body);
        };

        ReturnBibcode.prototype = new BaseModel();
        ReturnBibcode.prototype.constructor = ReturnBibcode;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ReturnBibcode.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'body', realName: 'body' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ReturnBibcode.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        ReturnBibcode.prototype.getBody = function () {
            return this.body;
        };
    
        /**
         * Setter for Body
         * 
         * @param {string} value 
         */
        ReturnBibcode.prototype.setBody = function (value) {
            this.body = value;
        };
    
        return ReturnBibcode;
    }

}(angular));
