/**
  * BibcodeQueryLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('BibcodeQueryLib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            BIBCODE_QUERY_PORT: 'BibcodeQueryPort'
        };
    }

}(angular));
